[package]
name = "ch8-mget"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.50"
rand = "0.9.2"
url = "2.5.7"
smoltcp = { version = "0.12.0", default-features = true, features = ["phy-tuntap_interface"] }
tun-tap = "0.1.0"
trust-dns-proto = "0.23.2"
